### ISSUE TITLE
Amélioration du systeme d'activité 

### ISSUE THREAD

**Issue by Bluzzi** [Virtual-Royaume/Royaume-API#27]
Le système d'activité est actuellement basé sur le nombre de messages et de temps en vocal durant le mois. Ce système devrait complètement changer et dépendre de son propre système : des points d'activité.

**Les points d'activité :** Il faudrait donc créer un nombre de points d'activité avec une requête permettant de l'incrémenter d'un montant voulu. Ce nombre de points d'activité serait réinitialiser tous les mois après que les changements de tier ai eu lieu.

**Les changements de rôle :** le plus haut tier doit être difficile à atteindre, pour l'obtenir, il faudrait à la fois faire partie des X% les plus actifs du serveur, mais aussi avoir au moins 2 fois l'activité moyenne des membres du serveur durant le mois. Dans le cas on l'on est déjà au plus haut tier, si l'on n'a pas au moins 2 fois l'activité moyenne des membres, on descend d'un rôle, de manière à ce qu'uniquement les membres qui restent les plus actifs puisse garder ce rôle.

**Comment by royaljacques** [comment]
Je propose de complêtement modifer l'agorythme .

le tris ne se ferais que par le biai du grade . 
l'algo ne change pas en sois , on garde le fait que les  + 30% montent et les - 30% déscendents. 

on pourrais aussi mêttre un taux de chance par rapport au grade du style : 
rank 5 : 100% de chance 
rank 4: 80% de chance 
rank 3: 60% de chance 
rank 2:40% de chance 
rank 1:20% de chance 

la commande serais
 /rank-top  `type (le même que la personne ou bien all`

on pourrais aussi rajouter un combo de rank en mode `cela  fait ** de temps  que ** est au rang 1`

je n'hésiterais pas a modifer ce texte si potentiellement j'ai d'autres idée.
